require_relative 'lib/currency'
require_relative 'lib/wallet'
require_relative 'lib/participant'
require_relative 'lib/player'
require_relative 'lib/dealer'
require_relative 'lib/shoe'
require_relative 'lib/deck'
require_relative 'lib/card'
require_relative 'lib/hand'
require_relative 'lib/rules'
require_relative 'lib/display'
require_relative 'lib/computation'
require_relative 'lib/game'

Game.new.start
